export function collectorSnippet(
  otlpEngineId: string,
  betterdbUrl: string,
  scrapeTarget = 'vllm:8000',
): string {
  return [
    'receivers:',
    '  prometheus:',
    '    config:',
    '      scrape_configs:',
    '        - job_name: lmcache',
    '          scrape_interval: 30s',
    '          static_configs:',
    `            - targets: ['${scrapeTarget}']`,
    'processors:',
    '  resource:',
    '    attributes:',
    '      - key: betterdb.lmcache.engine',
    `        value: ${otlpEngineId}`,
    '        action: upsert',
    'exporters:',
    '  otlphttp:',
    `    metrics_endpoint: ${betterdbUrl}/v1/external/metrics`,
    '    headers:',
    "      Authorization: 'Bearer ${env:BETTERDB_OTEL_INGEST_TOKEN}'",
    'service:',
    '  pipelines:',
    '    metrics:',
    '      receivers: [prometheus]',
    '      processors: [resource]',
    '      exporters: [otlphttp]',
    '',
  ].join('\n');
}
